config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :listings, only: %i[index create new update] do
    resources :offers, only: %i[create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/listing.rb
class Listing < ApplicationRecord
  belongs_to :user
  validates :text, presence: true
  validates :title, presence: true
  has_many_attached :photos
  has_many :offers, dependent: :destroy
end

app/models/offer.rb
class Offer < ApplicationRecord
  belongs_to :user
  belongs_to :listing
  validates :text, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :set_listing, only: [:update]
  def index
    @listings = Listing.all
  end

  def new
    @listing = Listing.new
  end

  def create
    @listing = Listing.new(listing_params)
    @listing.user = current_user
    @listing.save
    if @listing.save
      redirect_to listings_path, notice: 'added!'
    else
      render :new
    end
  end

  def update
    @listing.active = false
    if @listing.save
      redirect_to listings_path
    else
      render :index
    end
  end

  private

  def listing_params
    params.require(:listing).permit(:text, :title, photos: [])
  end

  def set_listing
    @listing = Listing.find(params[:id])
  end
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
  # before_action :set_listing, only: [:create, :update]
  def create
    @listing = Listing.find(params[:listing_id])
    @offer = Offer.new(offer_params)
    @offer.listing = @listing
    @offer.user = current_user
      if @offer.save
        redirect_to listings_path, notice: 'Your offer was successfully added.'
      else
        render :new
      end
  end

  # def update
  #   # @listing = Listing.find(params[:listing_id])
  #   @offer = Offer.find(params[:id])
  #   @listing.active = false
  #   if @offer.save
  #     redirect_to listings_path
  #   else
  #     render :index
  #   end
  # end

  private

  def offer_params
    params.require(:offer).permit(:text)
  end

  # def set_listing
  #   @listing = Listing.find(params[:listing_id])
  # end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tradeit</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
<link href="https://fonts.googleapis.com/css2?family=Lato:wght@300;700&display=swap" rel="stylesheet">
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>

    <%= yield %>
  </body>
</html>

app/views/listings/index.html.erb
<div class="listing-cards">
  <% @listings.order(created_at: :desc).each do |listing| %>
    <div class="listing-card">
      <% if listing.active == false%>
      <div class="listing-sold-banner">
        <p>this listing has been traded</p>
      </div>
      <% end %>
      <div class="photo-container">
        <% listing.photos.each do |photo| %>
          <%= cl_image_tag photo.key, height: 300, width: 400, crop: :fill %>
        <% end %>
      </div>
      <div class="listing-card-title">
        <%= listing.title.upcase %>
      </div>
      <div class="listing-card-details">
        <%= listing.text %>
      </div>
    <div class="offer-cards">
      <% listing.offers.each do |offer| %>
        <div class="offer-card">
          <%= offer.text %>
          <% if listing.user == current_user && listing.active%>
            <div class="choose-offer-button">
              <%= link_to 'choose this offer', listing_path(listing), method: :patch %>
            </div>
            <% elsif listing.user == current_user && listing.active == false %>
              <p class = 'cannot-choose-badge'>cannot choose</p>
          <% end %>
        </div>
      <% end %>
    </div>
    <% if listing.active %>
      <div id="new-offer-form">
        <%= simple_form_for [listing, Offer.new] do |f| %>
        <%= f.input :text, placeholder: 'What do you want to tradeit for?' %>
        <%= f.button :submit %>
        <% end %>
      </div>
      <% else %>
        <p class='text-center'> The seller has already selected an offer </p>
    <% end %>
   </div>
  <% end %>
</div>

app/views/listings/new.html.erb
<div>
  <%= simple_form_for [@listing] do |f| %>
    <%= f.input :title %>
    <%= f.input :text %>
    <%= f.input :photos, as: :file, input_html: { multiple: true } %>
    <%= f.button :submit %>
  <% end %>
</div>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to listings_path, class: "navbar-brand" do %>
    <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Add a Listing", new_listing_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Messages", "#", class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Action", "#", class: "dropdown-item" %>
            <%= link_to "Another action", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>